### ISSUE TITLE
Xcode cannot complete installation of RC1 package

### ISSUE THREAD

**Issue by idrougge** [adam-fowler/aws-cognito-authentication-kit#2]
Xcode 11.4 fails to resolve three packages, including BigNum.
Xcode 11.3.1 fails altogether to fetch tag `1.0.0-rc.1`.

Installing from `master` does work, but based on version number/release is the default option, so it caused me a lot of head-scratching.

**Comment by adam-fowler** [comment]
If you run `swift package resolve` does it work? There appears to be a load of issues with the target dependencies setup that are XCode specific. I've seen it reported in various placed on the internet. I'll have a look

**Comment by adam-fowler** [comment]
This should be fixed now

**Comment by idrougge** [comment]
Thank you, confirmed working!
