### ISSUE TITLE
No option to enable ADMIN_NO_SRP_AUTH

### ISSUE THREAD

**Issue by kingreza** [adam-fowler/aws-cognito-authentication-kit#5]
I am unable to get login to work in a Vapor app. Not sure if this is an issue with my approach or with the library. 
When I make the following call:

```
  app.post("login") { req -> EventLoopFuture<HTTPStatus> in
    struct UserSignIn: Content {
      let email: String
      let password: String
    }
    let user = try req.content.decode(UserSignIn.self)
    return app.awsCognito.authenticatable.authenticate(
      username: user.email,
      password: user.password,
      context: req,
      on: req.eventLoop).flatMap { response in
        return req.eventLoop.makeSucceededFuture(HTTPStatus.ok)
      }.flatMapErrorThrowing { error in
        guard let cognitoError = error as? CognitoIdentityProviderErrorType else {
          throw Abort(.internalServerError, reason: "unknown error with cognito: \(error.localizedDescription)")
        }
        throw Abort(.unauthorized, reason: cognitoError.localizedDescription)
      }
  }
```
I get the following error:
```
"User: arn:aws:iam::765243169499:user/podcast is not authorized to perform: cognito-idp:AdminInitiateAuth on resource: arn:aws:cognito-idp:us-west-2:765243169499:userpool/us-west-2_9D07yzMcr
```
In the [README](https://github.com/adam-fowler/aws-cognito-authentication-kit/blob/master/README.md#creating-user-pools) file for [aws-cognito-authentication-kit](https://github.com/adam-fowler/aws-cognito-authentication-kit/) says we need to have sign-in API for server-based authentication (ADMIN_NO_SRP_AUTH) enabled, but no such option is provided in the console:

![image](https://user-images.githubusercontent.com/2187641/88497775-332e8a00-cf76-11ea-8fed-1e39f89313e4.png)

Looking at the code in `authenticate` it's going the path of `adminNoSrpAuth` so I think the error might be related.

**Comment by kingreza** [comment]
Bypassing `authenticate` and making a `userPasswordAuth` through `initiateAuthRequest` gets the jobs done. What is being given up by not using `adminNoSrpAuth`? https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pool-managing-errors.html touches on these authentication flows but I couldn't find anything that answers that question. 

Also had to set `requireAuthentication` to false which is an oddly named parameter but the code seems to branch off making an `AdminInitiateAuthRequest` or a `InitiateAuthRequest` based on its value which I believe is the source of the error. 
```
    return app.awsCognito.authenticatable.secretHashFuture(
      username: user.email,
      on: req.eventLoop).flatMap { secretHash in
        let authParameters : [String: String] = ["USERNAME":user.email,
                                                 "PASSWORD": user.password,
                                                 "SECRET_HASH":secretHash]
      return app.awsCognito.authenticatable.initiateAuthRequest(
        authFlow: .userPasswordAuth,
        authParameters: authParameters,
        requireAuthentication: false,
        clientMetadata: nil,
        context: req,
        on: req.eventLoop).flatMap { response in
          return req.eventLoop.makeSucceededFuture(HTTPStatus.ok)
        }.flatMapErrorThrowing { error in
          //error handling..
        }
    }
```

**Comment by adam-fowler** [comment]
Hi Reza,

There are two paths in Cognito. One requires an authenticated client and one doesn't. An authenticated client has been provided with `accessKeyId` and `secretAccessKey`. There are many ways to supply credentials. See [here](https://github.com/swift-aws/aws-sdk-swift#compatibility) for more details.

An authenticated client has access to all the commands prefixed with `Admin` while an unauthenticated client doesn't. The authenticated clients are more designed to run from a server but there is nothing stopping you using an unauthenticated client from a server. The `requireAuthentication` flag in `initiateAuthRequest` will try to use the `Admin` commands when set to true, so you are required to supply an authenticated client for that to work. I guess I could improve the error handing here to be more informative.

It looks like AWS have changed their website since I wrote the docs for aws-cognito-authentication. The `ADMIN_NO_SRP_AUTH` flag is now called `ALLOW_ADMIN_USER_PASSWORD_AUTH`.

**Comment by kingreza** [comment]
Thanks for the thorough explanation. Since my usecase is on the backend where the client credentials can be safely stored, I should be able to make authenticate client calls. This is how my `authenticatable` is configured. My assumption was that once the client id and secret are provided that should be enough to authenticate the client with Cognito. However that is not the case..

```
  let awsCognitoConfiguration = AWSCognitoConfiguration(
    userPoolId: "us-west-2_9D07yzMcr",
    clientId: "536ctbdmtnvvb6vmaqc9tm6rkn",
    clientSecret: "hiq....",
    cognitoIDP: CognitoIdentityProvider(region: .uswest2),
    region: .uswest2
  )
 app.awsCognito.authenticatable = AWSCognitoAuthenticatable(configuration: awsCognitoConfiguration)
```
<img width="1175" alt="Screen Shot 2020-07-27 at 10 04 51 AM" src="https://user-images.githubusercontent.com/2187641/88570403-dd4af800-cff0-11ea-929b-480402589f71.png">

Is there anything else I need to do to get the admin calls to work?

**Comment by adam-fowler** [comment]
When you construct `CognitoIdentityProvider(region: .uswest2)` you need to provide IAM credentials `accessKeyId` and `secretAccessKey`. There are a number of of ways of providing these. As I pointed out above there are details about providing credentials [here](https://github.com/swift-aws/aws-sdk-swift#configuring-credentials).

I've just made a new release which has some breaking changes, so I renamed the `requireAuthentication` parameter to `requireAuthenticatedClient` to hopefully make it more obvious what it means.

**Comment by kingreza** [comment]
Ah now it makes sense. I need both a user AND a client. This was not evident in the README since the example just provides a `CognitoIdentityProvider(region: .uswest2)`. I think in makes sense to update https://github.com/adam-fowler/aws-cognito-authentication#configuration to include a `CognitoIdentityProvider` with `accessKeyId` and `secretAccessKey` for a user that has access to cognito since the calls for `authenticate` are admin based.

Adding that got it to work. Thanks for clarification.
