### ISSUE TITLE
Target support errors

### ISSUE THREAD

**Issue by SkyMatt70** [adam-fowler/aws-cognito-authentication-kit#7]
New project targeting iOS 14.1 fails to compile with the following after adding this package:

Showing Recent Errors Only

Build target AWSCognitoAuthenticationSRP with configuration Debug
error: The package product 'CognitoIdentity' requires minimum platform version 12.0 for the iOS platform, but this target supports 9.0 (in target 'AWSCognitoAuthenticationSRP' from project 'aws-cognito-authentication-kit')
error: The package product 'CognitoIdentityProvider' requires minimum platform version 12.0 for the iOS platform, but this target supports 9.0 (in target 'AWSCognitoAuthenticationSRP' from project 'aws-cognito-authentication-kit')
error: The package product 'JWTKit' requires minimum platform version 13.0 for the iOS platform, but this target supports 9.0 (in target 'AWSCognitoAuthenticationSRP' from project 'aws-cognito-authentication-kit')
error: The package product 'Crypto' requires minimum platform version 13.0 for the iOS platform, but this target supports 9.0 (in target 'AWSCognitoAuthenticationSRP' from project 'aws-cognito-authentication-kit')

Build target AWSCognitoAuthenticationKit with configuration Debug
error: The package product 'CognitoIdentity' requires minimum platform version 12.0 for the iOS platform, but this target supports 9.0 (in target 'AWSCognitoAuthenticationKit' from project 'aws-cognito-authentication-kit')
error: The package product 'CognitoIdentityProvider' requires minimum platform version 12.0 for the iOS platform, but this target supports 9.0 (in target 'AWSCognitoAuthenticationKit' from project 'aws-cognito-authentication-kit')
error: The package product 'JWTKit' requires minimum platform version 13.0 for the iOS platform, but this target supports 9.0 (in target 'AWSCognitoAuthenticationKit' from project 'aws-cognito-authentication-kit')
error: The package product 'Crypto' requires minimum platform version 13.0 for the iOS platform, but this target supports 9.0 (in target 'AWSCognitoAuthenticationKit' from project 'aws-cognito-authentication-kit')

**Comment by adam-fowler** [comment]
Up until recently aws-cognito-authentication-kit wouldn't compile on iOS because one of its dependencies, the package jwt-kit didn't compile for iOS. This looks like it has been resolved so we should be able to add an iOS platform for aws-cognito-authentication-kit and get it up and running. I'll look into getting something compiling today. 

I warn you though you'll be the first person to have it running on iOS so there maybe issues.

**Comment by adam-fowler** [comment]
I released v1.2.0 with iOS support, can you verify it works

**Comment by SkyMatt70** [comment]
Thanks Adam, it does now compile but haven't gotten far enough to give you an end to end thumbs up, but it's looking good!
